# Generated by Django 5.2.12 on 2026-04-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0007_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_source',
            field=models.CharField(choices=[('feed', 'Provided by feed'), ('extracted', 'Extracted from source article'), ('summary', 'Summary fallback'), ('empty', 'No readable content')], default='summary', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provided', 'Provided by feed'), ('success', 'Extraction succeeded'), ('failed', 'Extraction failed'), ('skipped', 'Extraction skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10),
        ),
    ]
