# Generated by Django 5.2.12 on 2026-04-11 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0008_article_content_source_article_extracted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='etag',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='fetch_interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_modified',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='next_fetch_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
