# Generated by Django 5.2.12 on 2026-04-12 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0010_bookmarkcategory_bookmark_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='hash',
            field=models.CharField(blank=True, default='', help_text='SHA256 hash for deduplication (url-based)', max_length=64),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='normalized_url',
            field=models.URLField(blank=True, db_index=True, default='', help_text='URL without tracking parameters for deduplication', max_length=2048),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Legacy category field (use category_v2 for new data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='rssapp.bookmarkcategory'),
        ),
        migrations.CreateModel(
            name='BookmarkUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_read_later', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='rssapp.bookmark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('content_type', models.CharField(choices=[('feed', 'Feed'), ('bookmark', 'Bookmark'), ('both', 'Both')], default='both', help_text='Which content types this category applies to', max_length=20)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category_v2',
            field=models.ForeignKey(blank=True, help_text='New unified category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='rssapp.category'),
        ),
        migrations.AddField(
            model_name='feed',
            name='category_v2',
            field=models.ForeignKey(blank=True, help_text='New unified category (category field for backward compatibility)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds', to='rssapp.category'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'normalized_url'], name='rssapp_book_user_id_18c12c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', 'created_at'], name='rssapp_book_user_id_d4e463_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['user', '-created_at'], name='rssapp_book_user_id_b7a0da_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_url__gt', '')), fields=('user', 'normalized_url'), name='uniq_user_bookmark_normalized_url'),
        ),
        migrations.AddIndex(
            model_name='bookmarkuserstate',
            index=models.Index(fields=['user', 'updated_at'], name='rssapp_book_user_id_d00b95_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkuserstate',
            index=models.Index(fields=['user', 'is_read_later'], name='rssapp_book_user_id_d3bc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkuserstate',
            index=models.Index(fields=['user', 'is_favorite'], name='rssapp_book_user_id_d9b094_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmarkuserstate',
            constraint=models.UniqueConstraint(fields=('user', 'bookmark'), name='uniq_bookmark_user_state'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_user_category_name'),
        ),
    ]
