# Generated by Django 5.2.12 on 2026-04-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssapp', '0012_add_extraction_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_display_mode',
            field=models.CharField(choices=[('list', 'List view'), ('compact', 'Compact view'), ('card', 'Card view')], default='compact', help_text='Default display mode for article and bookmark lists', max_length=20),
        ),
    ]
