# Generated by Django 5.2.12 on 2026-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rssapp", "0013_add_display_mode_to_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkuserstate",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
