# Generated by Django 5.2.12 on 2026-04-12 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rssapp", "0014_add_is_pinned_to_bookmarkuserstate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="articleuserstate",
            name="rssapp_arti_user_id_a28ea4_idx",
        ),
        migrations.RemoveField(
            model_name="articleuserstate",
            name="is_favorite",
        ),
        migrations.RemoveIndex(
            model_name="bookmarkuserstate",
            name="rssapp_book_user_id_d9b094_idx",
        ),
        migrations.RemoveField(
            model_name="bookmarkuserstate",
            name="is_favorite",
        ),
    ]
